# Generated by Django 5.2.3 on 2025-07-07 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
        ('platform_app', '0018_results_camera_perspective_results_camera_quality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptions',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='user',
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='platform_app.userprofiles'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactions',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform_app.userprofiles'),
        ),
    ]
