# Generated by Django 5.2.3 on 2025-06-24 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('answer', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'answers',
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('n8n_id', models.CharField(blank=True, max_length=10, null=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'interview_questions',
            },
        ),
        migrations.CreateModel(
            name='Interviews',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tier', models.CharField(blank=True, max_length=20, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('skor_keseluruhan', models.IntegerField(blank=True, null=True)),
                ('no_hp', models.CharField(blank=True, max_length=20, null=True)),
                ('posisi', models.CharField(blank=True, max_length=100, null=True)),
                ('domisili_saat_ini', models.CharField(blank=True, max_length=100, null=True)),
                ('industri', models.CharField(blank=True, max_length=100, null=True)),
                ('kekuatan', models.TextField(blank=True, null=True)),
                ('kelemahan', models.TextField(blank=True, null=True)),
                ('tools', models.TextField(blank=True, null=True)),
                ('pendidikan', models.TextField(blank=True, null=True)),
                ('pengalaman_relevan', models.TextField(blank=True, null=True)),
                ('portofolio', models.TextField(blank=True, null=True)),
                ('sertifikasi', models.TextField(blank=True, null=True)),
                ('years_of_experience', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interviews',
            },
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'schedules',
            },
        ),
        migrations.CreateModel(
            name='Evaluations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('rationale', models.TextField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='platform_app.answers')),
            ],
            options={
                'db_table': 'evaluations',
            },
        ),
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='platform_app.interviewquestions'),
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='platform_app.interviews')),
                ('final_score', models.IntegerField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'results',
            },
        ),
        migrations.AddField(
            model_name='interviewquestions',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='platform_app.interviews'),
        ),
        migrations.AddField(
            model_name='interviews',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='platform_app.schedules'),
        ),
    ]
