# Generated by Django 5.2.3 on 2025-06-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0002_remove_interviews_schedule_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
