# Generated by Django 5.2.3 on 2025-06-24 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0003_alter_session_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InterviewQuestions',
            new_name='Questions',
        ),
    ]
