# Generated by Django 5.2.3 on 2025-06-24 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0004_rename_interviewquestions_questions'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='questions',
            table='questions',
        ),
    ]
