# Generated by Django 5.2.3 on 2025-06-24 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0005_alter_questions_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviews',
            name='session',
        ),
        migrations.AddField(
            model_name='interviews',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviews',
            name='schedules',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='platform_app.schedules'),
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
