# Generated by Django 5.2.3 on 2025-06-24 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0007_remove_interviews_no_hp_userprofiles_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofiles',
            table='user_profiles',
        ),
    ]
