# Generated by Django 5.2.3 on 2025-06-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0008_alter_userprofiles_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviews',
            name='no_hp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
