# Generated by Django 5.2.3 on 2025-06-24 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0011_remove_interviews_no_hp_userprofiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviews',
            name='user',
        ),
        migrations.AddField(
            model_name='interviews',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='platform_app.userprofiles'),
        ),
    ]
