# Generated by Django 5.2.3 on 2025-06-24 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0012_remove_interviews_user_interviews_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviews',
            old_name='schedules',
            new_name='schedule',
        ),
    ]
