# Generated by Django 5.2.3 on 2025-06-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0013_rename_schedules_interviews_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviews',
            name='booking_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='interviews',
            name='jenis_wawancara',
            field=models.CharField(choices=[('Technical', 'Technical'), ('HR', 'HR'), ('Design', 'Design'), ('Management', 'Management'), ('Other', 'Other')], default='Technical', max_length=20),
        ),
        migrations.AddField(
            model_name='interviews',
            name='nama_perusahaan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interviews',
            name='tingkatan',
            field=models.CharField(choices=[('Entry', 'Entry'), ('Mid', 'Mid'), ('Senior', 'Senior'), ('Lead', 'Lead'), ('Manager', 'Manager')], default='Entry', max_length=10),
        ),
        migrations.AlterField(
            model_name='interviews',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='interviews',
            name='tier',
            field=models.CharField(choices=[('Free', 'Free'), ('Basic', 'Basic'), ('Premium', 'Premium')], default='Free', max_length=10),
        ),
    ]
