# Generated by Django 5.2.3 on 2025-06-26 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0015_interviews_detail_pekerjaan'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraAnalysis',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('multiple_faces', models.CharField(blank=True, max_length=15, null=True)),
                ('eye_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('face_visibility', models.CharField(blank=True, max_length=15, null=True)),
                ('general_expression', models.CharField(blank=True, max_length=15, null=True)),
                ('camera_quality', models.CharField(blank=True, max_length=15, null=True)),
                ('camera_perspective', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_app.interviews')),
            ],
            options={
                'db_table': 'camera_analysis',
            },
        ),
    ]
