# Generated by Django 5.2.3 on 2025-07-12 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_remove_subscriptions_user_remove_transactions_user_and_more'),
        ('platform_app', '0018_results_camera_perspective_results_camera_quality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviews',
            name='tier',
        ),
        migrations.AddField(
            model_name='interviews',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_app.packages'),
        ),
    ]
