# Generated by Django 5.2.3 on 2025-07-15 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0021_alter_userprofiles_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CVScreeningReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
                ('format_and_structure_score', models.IntegerField()),
                ('suitability_score', models.IntegerField()),
                ('experiences_score', models.IntegerField()),
                ('profile_summary_score', models.IntegerField()),
                ('work_experience_score', models.IntegerField()),
                ('education_score', models.IntegerField()),
                ('skills_score', models.IntegerField()),
                ('certifications_score', models.IntegerField()),
                ('projects_score', models.IntegerField()),
                ('achievements_score', models.IntegerField()),
                ('strengths', models.JSONField()),
                ('weaknesses', models.JSONField()),
                ('opportunities', models.JSONField()),
                ('threats', models.JSONField()),
                ('revisions', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cv_screening_reports',
            },
        ),
    ]
