# Generated by Django 5.2.3 on 2025-07-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0022_cvscreeningreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvscreeningreport',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
