# Generated by Django 5.2.3 on 2025-07-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0023_alter_cvscreeningreport_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvscreeningreport',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
