# Generated by Django 5.2.3 on 2025-07-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0024_cvscreeningreport_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvscreeningreport',
            name='grammar',
            field=models.JSONField(blank=True, default=''),
        ),
    ]
