# Generated by Django 5.2.3 on 2025-07-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0025_cvscreeningreport_grammar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviews',
            name='booking_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
