# Generated by Django 5.2.3 on 2025-07-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0026_alter_interviews_booking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvscreeningreport',
            name='score_justification',
            field=models.TextField(blank=True, default=''),
        ),
    ]
